name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PROJECT: ${{ github.repository }}

jobs:
  test:
    uses: linanok/linanok/.github/workflows/test.yml@main

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Web.Dockerfile
            image: web
          - dockerfile: QueueWorker.Dockerfile
            image: queue

    steps:
      - uses: actions/checkout@v4

      - name: Set Docker tags
        id: set_tags
        run: |
          IMAGE_PREFIX="${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ matrix.image }}"
          if [ "$GITHUB_EVENT_NAME" = "release" ]; then
            echo "tags<<EOF" >> $GITHUB_OUTPUT
            echo "${IMAGE_PREFIX}:${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            echo "${IMAGE_PREFIX}:latest" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "tags=${IMAGE_PREFIX}:unstable-${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ steps.set_tags.outputs.tags }}
