name: Build and Push Docker Images

on:
  push:
    branches: [ main, demo ]
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PROJECT: ${{ github.repository }}

jobs:
  test:
    permissions:
      contents: read
    uses: linanok/linanok/.github/workflows/test.yml@main

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: deployment/octane.Dockerfile
            image: octane
          - dockerfile: deployment/cli.Dockerfile
            image: cli
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ matrix.image }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=unstable-main,enable={{is_default_branch}}
            type=raw,value=unstable-demo,enable=${{ github.ref_name == 'demo' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.Dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VCS_REF=${{ github.sha }}
            VCS_URL=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
