name: Run Tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test-sqlite:
    uses: linanok/linanok/.github/workflows/test-sqlite.yml@main
  test-postgresql:
    uses: linanok/linanok/.github/workflows/test-postgresql.yml@main
